### ISSUE TITLE
Weekly Scrum - March 8th

### ISSUE THREAD

**Issue by ZoeticRose** [Jasenerd/SurveryMonkey4806#16]
Please comment all additions you make or plan to make during this week. Reminder that milestone one is due this week.

**Comment by omarazam98** [comment]
**What I have Done?**

- Connected Front End with Firebase Database
- Created Static Survey - Controllers/Models/Views

**What am I going to do next week?**

- Create dynamic survey controllers/Models/Templates
- Create survey database query's

What is holding me back?

Nothing

**Comment by ericcanam** [comment]
What have I done?
* Created relational database schema to model how the application will store and handle data.
* Troubleshot and fixed Heroku integration issue.

What am I going to do next week?
* Continue to work on data structure integration.

What is holding me back?
* Nothing at the moment.

**Comment by Jasenerd** [comment]
What I have Done?

- Set up CircleCI and Heroku automation.
- Some troubleshooting with test cases

What am I going to do next week?

- Increase the number of tests
- Improve code readability

What is holding me back?

My health is in a extremely poor state, leading to lost productivity.
