### ISSUE TITLE
Weekly Scrum - April 6th

### ISSUE THREAD

**Issue by HazelGriffith** [Jasenerd/SurveryMonkey4806#42]
What have you done?
What are you going to do next week?
What is holding you back?

**Comment by HazelGriffith** [comment]
What I have Done?

- Updated Class Diagram
- Updated Flow Chart

What am I going to do next week?

- This is the last milestone

What is holding me back?

I still have covid

**Comment by ericcanam** [comment]
**What have I done?**
- Fixed issue with survey submission (not all responses are recorded in rare cases)
- Fixed bug with range question creation
- Added histograms to survey report page
- Created methods to allow multiple CanvasJS instances to be generated on one page

**What am I going to do next week?**
- Nothing, we're done! :)

**What is holding me back?**
- It's a beautiful day outside. Hard to focus.

**Comment by ZoeticRose** [comment]
What have I done?

- Quality of Life Changes
- General polish on the html
- Some light testing

Next Week?
The Project is Complete

What is holding me back?

Nothing major, just time constraints.

**Comment by omarazam98** [comment]
Closed
